### ISSUE TITLE
[Produtos/Vendas] Pipe de currency

### ISSUE THREAD

**Issue by JuAintablian** [JuAintablian/front-controle-estoque#46]
Adicionar pipe de moeda nas tabelas de **produto**, coluna **preço** e de **vendas**, coluna **valor**

**Comment by gleisonkz** [comment]
solved on 3f37285026018e5fb8229aef79704b5205ca71ac

**Comment by gleisonkz** [comment]
solved on 3f37285026018e5fb8229aef79704b5205ca71ac

**Comment by gleisonkz** [comment]
solved on 3f37285026018e5fb8229aef79704b5205ca71ac
